apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lx1u1egwk-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-dc74fd47a1.wfkb.p3.openshiftapps.com/rhtap/rhtap-qe-dotnet-basic:fe13c8de5b00c34ba7783b0f4ce929c79a53e0cb@sha256:a3e4ed5aafd665c1028948aa7dc24df0d5fb925e3a7b2f35b178336f218825c4
          name: container-image
